version: '3.8'

services:
  tensorflow:
    image: ihl-harbor.apps.innovate.sg-cna.com/teck-xuan/tensorflow:v1
    build:
      context: ./model
    volumes:
      - ./dataset/test/demo:/app/dataset/test/demo
    ports:
      - "8080:8080"
    command: ["/opt/venv/bin/python", "app/main.py"]

  frontend:
    image: ihl-harbor.apps.innovate.sg-cna.com/teck-xuan/frontend:v1
    build:
      context: ./frontend
    ports:
      - "3000:3000"
